//! Generate declarative Nix configurations for all supported DEs.
//!
//! Each DE has a dedicated function that writes a complete, ready-to-build
//! Home Manager + NixOS module set.

use anyhow::Result;
use colored::Colorize;
use std::path::Path;

use crate::desktop::detect::DesktopEnv;
use crate::desktop::gnome;

/// Generate a complete declarative configuration for a desktop environment.
pub async fn generate_de(
    de: &DesktopEnv,
    config_dir: &Path,
    user: &str,
    from_live: bool,
) -> Result<()> {
    match de {
        DesktopEnv::GNOME => {
            if from_live {
                gnome::generate_from_dconf(config_dir, user).await
            } else {
                generate_gnome_template(config_dir, user).await
            }
        }
        DesktopEnv::KDE => generate_kde(config_dir, user).await,
        DesktopEnv::Hyprland => generate_hyprland(config_dir, user).await,
        DesktopEnv::Sway => generate_sway(config_dir, user).await,
        DesktopEnv::i3 => generate_i3(config_dir, user).await,
        DesktopEnv::Niri => generate_niri(config_dir, user).await,
        DesktopEnv::Cinnamon => generate_cinnamon(config_dir, user).await,
        DesktopEnv::XFCE => generate_xfce(config_dir, user).await,
        DesktopEnv::PopOS => generate_popos(config_dir, user).await,
        DesktopEnv::QuickShell => generate_quickshell(config_dir, user).await,
        DesktopEnv::Noctalia => generate_noctalia(config_dir, user).await,
        DesktopEnv::DankLinux => generate_danklinux(config_dir, user).await,
        DesktopEnv::Unknown(s) => {
            println!(
                "{} Unknown desktop '{}'. Generating minimal template.",
                "⚠".yellow(),
                s
            );
            generate_generic_template(config_dir, user, s).await
        }
    }
}

// ──────────────────────────
//  GNOME (from template)
// ──────────────────────────
async fn generate_gnome_template(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let content = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./gnome-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), content).await?;

    let settings_dir = desktop_dir.join("gnome-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    // default.nix for gnome-settings
    let default = r##"# Generated by i-nix desktop generate gnome
# Do not hand-edit; re-run `i-nix desktop generate gnome` instead.

{ ... }:

{
  imports = [
    ./gtk.nix
    ./shell.nix
    ./shell-extensions.nix
  ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default).await?;

    // gtk.nix
    let gtk = r##"# Generated by i-nix desktop generate gnome
{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/desktop/interface" = {
      clock-format = "24h";
      gtk-theme = "Adwaita";
      icon-theme = "Adwaita";
      cursor-theme = "Adwaita";
      enable-hot-corners = true;
    };
    "org/gnome/desktop/background" = {
      picture-uri = "file:///run/current-system/sw/share/backgrounds/gnome/vortex-gnome-l.jpg";
    };
  };
}"##;
    tokio::fs::write(settings_dir.join("gtk.nix"), gtk).await?;

    // shell.nix
    let shell = r##"# Generated by i-nix desktop generate gnome
{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/shell" = {
      favorite-apps = [ "firefox.desktop" "org.gnome.Nautilus.desktop" "org.gnome.Console.desktop" ];
      disable-user-extensions = false;
    };
    "org/gnome/shell/keybindings" = {
      toggle-overview = [ "<Super>a" ];
    };
  };
}"##;
    tokio::fs::write(settings_dir.join("shell.nix"), shell).await?;

    // shell-extensions.nix
    let shell_ext = r##"# Generated by i-nix desktop generate gnome
{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/shell/extensions/user-theme" = {
      name = "";
    };
  };
}"##;
    tokio::fs::write(settings_dir.join("shell-extensions.nix"), shell_ext).await?;

    println!();
    println!("✓ Generated GNOME declarative configuration");
    println!("  {} {}", "Directory:".dimmed(), settings_dir.display());
    println!();
    println!("  {}", "Run `i-nix desktop detect` then `i-nix apply`.".dimmed());
    println!();

    Ok(())
}

// ──────────────────────────
//  KDE PLASMA
// ──────────────────────────
async fn generate_kde(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  # Enable Plasma 6
  programs.plasma.enable = true;

  # Import KDE-specific settings
  imports = [ ./kde-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("kde-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate kde
{ lib, ... }:

{
  programs.plasma = {
    configFile = {
      "kwinrc"."Windows"."BorderlessMaximizedWindows" = true;
      "kwinrc"."Desktops"."Number" = 4;
      "kwinrc"."Desktops"."Rows" = 1;
      "kcmfonts"."General"."font" = "Noto Sans,10,-1,5,50,0,0,0,0,0";
    };
  };
}"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated KDE Plasma configuration");
    Ok(())
}

// ──────────────────────────
//  HYPRLAND
// ──────────────────────────
async fn generate_hyprland(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./hyprland-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("hyprland-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate hyprland
{ config, pkgs, lib, ... }:

{
  programs.hyprland = {
    enable = true;
    settings = {
      monitor = ",preferred,auto,auto";

      exec-once = [
        "waybar"
        "mako"
      ];

      general = {
        gaps_in = 5;
        gaps_out = 10;
        border_size = 2;
        "col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
        "col.inactive_border" = "rgba(595959aa)";
        layout = "dwindle";
      };

      decoration = {
        rounding = 10;
        blur = {
          enabled = true;
          size = 3;
          passes = 1;
        };
        drop_shadow = true;
        shadow_range = 4;
        shadow_render_power = 3;
        "col.shadow" = "rgba(1a1a1aee)";
      };

      animations = {
        enabled = true;
        bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
        animation = [
          "windows, 1, 7, myBezier"
          "windowsOut, 1, 7, default, popin 80%"
          "border, 1, 10, default"
          "fade, 1, 7, default"
          "workspaces, 1, 6, default"
        ];
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      master = {
        new_is_master = true;
      };

      input = {
        kb_layout = "us";
        follow_mouse = 1;
        touchpad.natural_scroll = true;
      };

      "$mod" = "SUPER";
      bind = [
        "$mod, RETURN, exec, kitty"
        "$mod, Q, killactive,"
        "$mod, M, exit,"
        "$mod, V, togglefloating,"
        "$mod, R, exec, rofi -show drun"
        "$mod, P, pseudo,"
        "$mod, J, togglesplit,"
        "$mod, left, movefocus, l"
        "$mod, right, movefocus, r"
        "$mod, up, movefocus, u"
        "$mod, down, movefocus, d"
      ];
      bindm = [
        "$mod, mouse:272, movewindow"
        "$mod, mouse:273, resizewindow"
      ];
    };
  };

  services.hypridle.enable = true;
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated Hyprland configuration");
    Ok(())
}

// ──────────────────────────
//  SWAY
// ──────────────────────────
async fn generate_sway(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./sway-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("sway-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate sway
{ config, pkgs, lib, ... }:

{
  wayland.windowManager.sway = {
    enable = true;
    config = {
      modifier = "Mod4";
      terminal = "kitty";
      menu = "rofi -show drun";

      gaps = {
        inner = 10;
        outer = 5;
      };

      window = {
        border = 2;
        titlebar = false;
      };

      bars = [];
    };
  };

  programs.waybar.enable = true;
  services.mako.enable = true;
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated Sway configuration");
    Ok(())
}

// ──────────────────────────
//  i3
// ──────────────────────────
async fn generate_i3(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./i3-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("i3-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate i3
{ config, pkgs, lib, ... }:

{
  xsession.windowManager.i3 = {
    enable = true;
    config = {
      modifier = "Mod4";
      terminal = "kitty";
      menu = "rofi -show drun";

      gaps = {
        inner = 10;
        outer = 5;
      };

      window = {
        border = 2;
        titlebar = false;
      };

      bars = [];
    };
  };

  services.polybar.enable = true;
  services.dunst.enable = true;
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated i3 configuration");
    Ok(())
}

// ──────────────────────────
//  NIRI
// ──────────────────────────
async fn generate_niri(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./niri-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("niri-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate niri
{ config, pkgs, lib, ... }:

{
  programs.niri = {
    enable = true;
    settings = {
      input.keyboard.xkb.layout = "us";
      input.touchpad.natural-scroll = true;

      outputs."eDP-1".scale = 1.0;

      layout = {
        gaps = 8;
        border.width = 2;
        "border.active.color" = "#7fc8ff";
        "border.inactive.color" = "#4a4a4a";
      };

      binds = {
        "Mod+Return".action.spawn = [ "kitty" ];
        "Mod+Q".action = "close-window";
        "Mod+M".action = "quit";
        "Mod+R".action.spawn = [ "rofi", "-show", "drun" ];
        "Mod+Left".action = "focus-column-left";
        "Mod+Right".action = "focus-column-right";
        "Mod+Up".action = "focus-window-up";
        "Mod+Down".action = "focus-window-down";
      };
    };
  };
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated Niri configuration");
    Ok(())
}

// ──────────────────────────
//  CINNAMON
// ──────────────────────────
async fn generate_cinnamon(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  services.xserver.desktopManager.cinnamon.enable = true;
  imports = [ ./cinnamon-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("cinnamon-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate cinnamon
{ lib, ... }:

{
  # Cinnamon settings via dconf
  dconf.settings = {
    "org/cinnamon/desktop/interface" = {
      clock-format = "24h";
    };
  };
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated Cinnamon configuration");
    Ok(())
}

// ──────────────────────────
//  XFCE
// ──────────────────────────
async fn generate_xfce(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  services.xserver.desktopManager.xfce.enable = true;
  imports = [ ./xfce-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("xfce-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate xfce
{ lib, ... }:

{
  # XFCE settings via dconf
  dconf.settings = {
    "org/xfce/desktop/interface" = {
      gtk-theme = "Adwaita";
    };
  };
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated XFCE configuration");
    Ok(())
}

// ──────────────────────────
//  POP!_OS COSMIC
// ──────────────────────────
async fn generate_popos(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  # COSMIC is still in alpha; use pop-shell on GNOME for now
  imports = [ ./popos-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("popos-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate popos
{ config, pkgs, lib, ... }:

{
  # Pop!_OS Shell (tiling extension on GNOME)
  programs.pop-shell = {
    enable = true;
  };

  dconf.settings = {
    "org/gnome/shell/extensions/pop-shell" = {
      show-title = true;
      tile-by-default = true;
      active-hint = true;
    };
  };
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated Pop!_OS configuration");
    Ok(())
}

// ──────────────────────────
//  QUICKSHELL
// ──────────────────────────
async fn generate_quickshell(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./quickshell-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("quickshell-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate quickshell
{ config, pkgs, lib, ... }:

{
  # QuickShell — declarative QtQuick desktop shell
  # See: https://quickshell.org/
  programs.quickshell = {
    enable = true;
    config = {
      bar = {
        position = "top";
        height = 32;
      };
    };
  };
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated QuickShell configuration");
    Ok(())
}

// ──────────────────────────
//  NOCTALIA
// ──────────────────────────
async fn generate_noctalia(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./noctalia-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("noctalia-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate noctalia
{ config, pkgs, lib, ... }:

{
  # Noctalia Shell — tiling Wayland compositor
  # See: https://github.com/noctalia-shell
  programs.noctalia = {
    enable = true;
    settings = {
      general = {
        mod-key = "Mod4";
        terminal = "kitty";
        menu = "rofi -show drun";
      };

      gaps = {
        inner = 5;
        outer = 0;
      };

      window = {
        border-width = 2;
        "active-border-color" = "#7fc8ff";
        "inactive-border-color" = "#4a4a4a";
      };

      keybindings = [
        { keys = ["Mod4", "Return"]; command = "spawn"; args = ["kitty"]; }
        { keys = ["Mod4", "q"]; command = "close-window"; }
        { keys = ["Mod4", "r"]; command = "spawn"; args = ["rofi", "-show", "drun"]; }
      ];
    };
  };
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated Noctalia configuration");
    Ok(())
}

// ──────────────────────────
//  DANKLINUX
// ──────────────────────────
async fn generate_danklinux(config_dir: &Path, user: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
{{ config, pkgs, lib, ... }}:

{{
  imports = [ ./danklinux-settings ];
}}
"##,
        user = user
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    let settings_dir = desktop_dir.join("danklinux-settings");
    tokio::fs::create_dir_all(&settings_dir).await?;

    let config = r##"# Generated by i-nix desktop generate danklinux
{ config, pkgs, lib, ... }:

{
  # DankLinux Shell — custom Wayland compositor
  # See: https://github.com/danklinux/dank-shell
  programs.dank-shell = {
    enable = true;
    settings = {
      compositor = {
        backend = "wayland";
        renderer = "vulkan";
      };

      appearance = {
        theme = "dark";
        accent-color = "#ff6b6b";
        border-radius = 8;
      };

      bar = {
        position = "top";
        modules-left = ["workspaces"];
        modules-center = ["clock"];
        modules-right = ["battery", "network"];
      };
    };
  };
}
"##;
    tokio::fs::write(settings_dir.join("config.nix"), config).await?;

    let default_import = r##"{ ... }:

{
  imports = [ ./config.nix ];
}"##;
    tokio::fs::write(settings_dir.join("default.nix"), default_import).await?;

    println!("✓ Generated DankLinux configuration");
    Ok(())
}

// ──────────────────────────
//  GENERIC / UNKNOWN
// ──────────────────────────
async fn generate_generic_template(config_dir: &Path, user: &str, name: &str) -> Result<()> {
    let desktop_dir = config_dir.join(format!("flake/users/{}/desktop", user));
    tokio::fs::create_dir_all(&desktop_dir).await?;

    let default_nix = format!(
        r##"# Desktop environment configuration for: {user}
# Custom/Unknown DE: {name}
{{ config, pkgs, lib, ... }}:

{{
  # Add your DE-specific configuration here.
  # See the NixOS Wiki for module options.
}}
"##,
        user = user,
        name = name
    );
    tokio::fs::write(desktop_dir.join("default.nix"), default_nix).await?;

    println!("✓ Generated minimal template for: {}", name);
    Ok(())
}
