use anyhow::Result;
use std::path::Path;

use crate::config::InstallTarget;
use crate::nixast::{PackageEntry, read_system_packages, read_home_packages, write_system_packages, write_home_packages};

/// NixEngine — the bridge between user intent and Nix configuration.
pub struct NixEngine<'a> {
    config_dir: &'a Path,
    hostname: &'a str,
    username: &'a str,
}

impl<'a> NixEngine<'a> {
    pub fn new(config_dir: &'a Path, hostname: &'a str, username: &'a str) -> Self {
        NixEngine {
            config_dir,
            hostname,
            username,
        }
    }

    /// Initialize the full flake directory structure with templates.
    pub fn init(&self, mode: &str, _with_home_manager: bool) -> Result<()> {
        let flake_dir = self.config_dir.join("flake");
        let _ = std::fs::create_dir_all(&flake_dir);

        // Create subdirectories
        let dirs = [
            "hosts", "systems", "modules/system", "modules/home",
            "home", "overlays", "pkgs", "lib",
        ];
        for d in &dirs {
            let _ = std::fs::create_dir_all(flake_dir.join(d));
        }

        // ── flake.nix ──
        let flake_nix = format!(
            r#"{{
  description = "Declarative NixOS configuration managed by i-nix for host: {}";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager = {{
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    }};

    flake-parts = {{
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    }};
  }};

  outputs = inputs @ {{ self, nixpkgs, home-manager, flake-parts, ... }}:
    flake-parts.lib.mkFlake {{ inherit inputs; }} {{
      systems = [ "x86_64-linux" "aarch64-linux" ];

      imports = [
        ./hosts/{}.nix
      ];

      perSystem = {{ config, pkgs, system, ... }}: {{
        packages = import ./pkgs {{ inherit pkgs; }};

        devShells.default = pkgs.mkShell {{
          nativeBuildInputs = with pkgs; [
            nixpkgs-fmt
            nixd
          ];
        }};
      }};
    }};
}}
"#,
            self.hostname, self.hostname
        );
        std::fs::write(flake_dir.join("flake.nix"), flake_nix)?;

        // ── host configuration ──
        let host_nix = format!(
            r#"# i-nix host configuration: {}
{{ self, inputs, config, lib, pkgs, ... }}: {{
  flake.nixosConfigurations.{} = inputs.nixpkgs.lib.nixosSystem {{
    system = "x86_64-linux";
    specialArgs = {{ inherit inputs self; }};
    modules = [
      ../systems/default.nix
      ../modules/system
      {{ nixpkgs.overlays = [ (import ../overlays) ]; }}
      inputs.home-manager.nixosModules.home-manager
      {{
        home-manager.useGlobalPkgs = true;
        home-manager.useUserPackages = true;
        home-manager.users.{} = import ../home/default.nix;
      }}
    ];
  }};
}}
"#,
            self.hostname, self.hostname, self.username
        );
        std::fs::write(flake_dir.join(format!("hosts/{}.nix", self.hostname)), host_nix)?;

        // ── systems/default.nix ──
        let system_nix = format!(
            r#"# i-nix generated system configuration
# Host: {}
# Do not edit this file directly — use `i-nix install/remove`
# Manual edits are supported: run `i-nix apply` after editing

{{ config, pkgs, lib, ... }}:

{{
  # ── Host identity ──
  networking.hostName = "{}";

  # ── Boot ──
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Locale ──
  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── System packages (declaratively managed) ──
  environment.systemPackages = with pkgs; [
  ];

  # ── Services ──
  # No services configured yet.
  # Use: i-nix enable <service>

  # ── Programs ──
  # No programs configured yet.
  # Use: i-nix enable --program <program>

  # ── System state version ──
  system.stateVersion = "24.11";

  # ── User account (managed by i-nix) ──
  # This creates a basic user. Customize in systems/default.nix or modules.
  users.users.{} = {{
    isNormalUser = true;
    group = "{}";
    extraGroups = [ "wheel" "networkmanager" ];
  }};
  users.groups.{} = {{ }};
}}
"#,
            self.hostname, self.hostname, self.username, self.username, self.username
        );
        std::fs::write(flake_dir.join("systems/default.nix"), system_nix)?;

        // ── home/default.nix ──
        let home_nix = format!(
            r#"# i-nix generated home configuration
# User: {}
# Do not edit this file directly — use `i-nix install --user`
# Manual edits are supported: run `i-nix apply` after editing

{{ config, pkgs, lib, ... }}:

{{
  home.username = "{}";
  # homeDirectory is managed by NixOS when using home-manager.nixosModules
  # Do NOT set home.homeDirectory here — it conflicts with NixOS user config
  home.stateVersion = "24.11";

  # ── User packages (declaratively managed) ──
  home.packages = with pkgs; [
  ];

  # ── Dotfiles ──
  # i-nix supports both:
  #   1. home-manager native options (programs.*.enable + settings)
  #   2. Plain dotfile sources managed via home.file
  #
  # For maximum compatibility, plain dotfiles are preferred for:
  #   - Complex configs that HM doesn't handle well
  #   - Editor configs (neovim, helix)
  #   - Terminal configs (kitty, alacritty)
  #   - Shell configs (bash, zsh, fish)
  #
  # Example:
  # home.file.".config/kitty/kitty.conf".source = ./dotfiles/kitty.conf;
}}
"#,
            self.username, self.username
        );
        std::fs::write(flake_dir.join("home/default.nix"), home_nix)?;

        // ── other boilerplate files ──
        let empty_nix = "{ config, pkgs, lib, ... }:\n\n{\n  # Placeholder module\n}\n";
        std::fs::write(flake_dir.join("modules/system/default.nix"), empty_nix)?;
        std::fs::write(flake_dir.join("modules/home/default.nix"), "{ }: { }\n")?;
        std::fs::write(flake_dir.join("overlays/default.nix"), "final: prev: { }\n")?;
        std::fs::write(flake_dir.join("pkgs/default.nix"), "{ pkgs }: { }\n")?;
        std::fs::write(flake_dir.join("lib/helpers.nix"), "{ lib, ... }: { }\n")?;

        // .gitignore
        std::fs::write(flake_dir.join(".gitignore"), "result\nresult-*\n")?;

        Ok(())
    }

    fn systems_nix(&self) -> std::path::PathBuf {
        self.config_dir.join("flake/systems/default.nix")
    }

    fn home_nix(&self) -> std::path::PathBuf {
        self.config_dir.join("flake/home/default.nix")
    }

    /// Add a package to the declarative configuration.
    pub fn add_package(&self, name: &str, _attr: &str, target: InstallTarget) -> Result<()> {
        match target {
            InstallTarget::System => {
                let path = self.systems_nix();
                let mut packages = read_system_packages(&path)?;
                if !packages.contains(&name.to_string()) {
                    packages.push(name.to_string());
                }
                let entries: Vec<PackageEntry> = packages.into_iter()
                    .map(|n| PackageEntry { name: n, comment: None })
                    .collect();
                write_system_packages(&path, &entries)?;
            }
            InstallTarget::User => {
                let path = self.home_nix();
                let mut packages = read_home_packages(&path)?;
                if !packages.contains(&name.to_string()) {
                    packages.push(name.to_string());
                }
                let entries: Vec<PackageEntry> = packages.into_iter()
                    .map(|n| PackageEntry { name: n, comment: None })
                    .collect();
                write_home_packages(&path, &entries)?;
            }
        }
        Ok(())
    }

    /// Remove a package from the declarative configuration.
    pub fn remove_package(&self, name: &str, target: InstallTarget) -> Result<bool> {
        let removed = match target {
            InstallTarget::System => {
                let path = self.systems_nix();
                let mut packages = read_system_packages(&path)?;
                let before = packages.len();
                packages.retain(|p| p != name);
                let after = packages.len();
                if after < before {
                    let entries: Vec<PackageEntry> = packages.into_iter()
                        .map(|n| PackageEntry { name: n, comment: None })
                        .collect();
                    write_system_packages(&path, &entries)?;
                    true
                } else {
                    false
                }
            }
            InstallTarget::User => {
                let path = self.home_nix();
                let mut packages = read_home_packages(&path)?;
                let before = packages.len();
                packages.retain(|p| p != name);
                let after = packages.len();
                if after < before {
                    let entries: Vec<PackageEntry> = packages.into_iter()
                        .map(|n| PackageEntry { name: n, comment: None })
                        .collect();
                    write_home_packages(&path, &entries)?;
                    true
                } else {
                    false
                }
            }
        };
        Ok(removed)
    }
}
