use anyhow::Result;
use std::path::Path;

use crate::config::InstallTarget;
use crate::nixast::{
    PackageEntry, read_system_packages, read_home_packages, write_system_packages, write_home_packages,
};

/// NixEngine — the bridge between user intent and Nix configuration.
///
/// Generates a production-grade, dendritic, multi-host directory structure:
///
/// ```text
/// ~/.config/i-nix/
/// ├── flake/
/// │   ├── flake.nix              # flake-parts entrypoint (defines nixosConfigurations)
/// │   ├── flake.lock             # pinned inputs
/// │   ├── hosts/                 # one file per physical machine
/// │   │   ├── laptop.nix
/// │   │   └── server.nix
/// │   ├── systems/               # per-host system configuration
/// │   │   ├── _common.nix        # shared base (boot, locale, nix settings)
/// │   │   ├── laptop/
/// │   │   │   ├── default.nix    # host-specific settings
/// │   │   │   └── hardware.nix   # hardware config (generated)
/// │   │   └── server/
/// │   │       └── default.nix
/// │   ├── users/                 # per-user home-manager configurations
/// │   │   └── lin/
/// │   │       ├── default.nix    # entrypoint: imports all sub-modules
/// │   │       ├── packages.nix   # user packages
/// │   │       ├── programs.nix   # enabled programs (git, firefox, kitty...)
/// │   │       ├── services.nix   # user services (syncthing, mpd...)
/// │   │       ├── desktop/        # desktop environment (DE/WM)
/// │   │       │   ├── default.nix # imports chosen DE
/// │   │       │   ├── gnome.nix   # generated by nix-my-gnome
/// │   │       │   ├── kde.nix
/// │   │       │   ├── hyprland.nix
/// │   │       │   └── sway.nix
/// │   │       ├── shells/         # shell configuration (bash, zsh, fish)
/// │   │       │   └── default.nix
/// │   │       ├── secrets/        # sops-nix or agenix managed secrets
/// │   │       │   └── default.nix
/// │   │       └── dotfiles/       # plain dotfile sources (not tracked by HM)
/// │   ├── modules/                # reusable NixOS modules
/// │   │   ├── system/             # system-level modules (network, security)
/// │   │   │   └── default.nix
/// │   │   └── home/               # home-manager modules
/// │   │       └── default.nix
/// │   ├── profiles/               # feature bundles (composable)
/// │   │   ├── core.nix            # minimal headless
/// │   │   ├── desktop.nix         # graphical system
/// │   │   ├── development.nix     # dev tools
/// │   │   ├── gaming.nix          # gaming stack
/// │   │   └── server.nix          # server stack
/// │   ├── overlays/               # nixpkgs overlays
/// │   │   └── default.nix
/// │   ├── pkgs/                   # custom package definitions
/// │   │   └── default.nix
/// │   └── lib/                    # helper functions
/// │       └── helpers.nix
/// └── state.json                  # i-nix metadata (not source of truth)
/// ```
pub struct NixEngine<'a> {
    config_dir: &'a Path,
    hostname: &'a str,
    username: &'a str,
}

impl<'a> NixEngine<'a> {
    pub fn new(config_dir: &'a Path, hostname: &'a str, username: &'a str) -> Self {
        NixEngine {
            config_dir,
            hostname,
            username,
        }
    }

    /// Initialize the full flake directory structure with templates.
    pub fn init(&self, _mode: &str, _with_home_manager: bool) -> Result<()> {
        let flake_dir = self.config_dir.join("flake");
        let _ = std::fs::create_dir_all(&flake_dir);

        // ── Create directory tree ──
        let dirs: Vec<String> = vec![
            "hosts".to_string(),
            format!("systems/{}", self.hostname),
            "users".to_string(),
            format!("users/{}", self.username),
            format!("users/{}/desktop", self.username),
            format!("users/{}/shells", self.username),
            format!("users/{}/secrets", self.username),
            format!("users/{}/dotfiles", self.username),
            format!("users/{}/packages", self.username),
            format!("users/{}/programs", self.username),
            format!("users/{}/services", self.username),
            "modules/system".to_string(),
            "modules/home".to_string(),
            "profiles".to_string(),
            "overlays".to_string(),
            "pkgs".to_string(),
            "lib".to_string(),
        ];
        for d in &dirs {
            let _ = std::fs::create_dir_all(flake_dir.join(d));
        }

        // ── flake.nix (flake-parts root) ──
        let flake_nix = format!(
            r#"{{
  description = "Declarative NixOS configuration managed by i-nix";

  inputs = {{
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager = {{
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    }};

    flake-parts = {{
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    }};
  }};

  outputs = inputs @ {{ self, nixpkgs, home-manager, flake-parts, ... }}:
    flake-parts.lib.mkFlake {{ inherit inputs; }} {{
      systems = [ "x86_64-linux" "aarch64-linux" ];

      flake = {{
        # ── NixOS configurations (one per host) ──
        nixosConfigurations = import ./hosts {{
          inherit inputs self;
        }};
      }};

      perSystem = {{ config, pkgs, system, ... }}: {{
        # Custom packages exposed by this flake
        packages = import ./pkgs {{ inherit pkgs; }};

        # Development shell for working on this config
        devShells.default = pkgs.mkShell {{
          nativeBuildInputs = with pkgs; [
            nixpkgs-fmt
            nixd
          ];
        }};
      }};
    }};
}}
"#
        );
        std::fs::write(flake_dir.join("flake.nix"), flake_nix)?;

        // ── hosts/default.nix (nixosConfigurations registry) ──
        let hosts_default = format!(
            r#"# i-nix hosts registry
# Each attribute defines one physical machine.
# Add new hosts by running: i-nix init --hostname <new-host>

{{ inputs, self, ... }}: {{
  {host} = inputs.nixpkgs.lib.nixosSystem {{
    system = "x86_64-linux";
    specialArgs = {{ inherit inputs self; }};
    modules = [
      # ── Base system ──
      ../systems/_common.nix
      ../systems/{host}

      # ── Custom overlays ──
      {{ nixpkgs.overlays = [ (import ../overlays) ]; }}

      # ── Home Manager ──
      inputs.home-manager.nixosModules.home-manager
      {{
        home-manager.useGlobalPkgs = true;
        home-manager.useUserPackages = true;
        home-manager.users.{user} = import ../users/{user};
      }}
    ];
  }};
}}
"#,
            host = self.hostname,
            user = self.username
        );
        std::fs::write(flake_dir.join("hosts/default.nix"), hosts_default)?;

        // ── systems/_common.nix (shared base across ALL hosts) ──
        let common_nix = r#"# i-nix common system base
# Shared across ALL hosts. Host-specific overrides go in systems/<host>/.

{ config, pkgs, lib, ... }:

{
  # ── Boot ──
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Locale ──
  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── System state version ──
  system.stateVersion = "24.11";

  # ── Nix settings ──
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.auto-optimise-store = true;
}
"#;
        std::fs::write(flake_dir.join("systems/_common.nix"), common_nix)?;

        // ── systems/<hostname>/default.nix ──
        let system_nix = format!(
            r#"# i-nix system configuration for: {host}
# Host-specific settings. Import profiles and modules here.

{{ config, pkgs, lib, ... }}:

{{
  # ── Host identity ──
  networking.hostName = "{host}";

  # ── User account ──
  users.users.{user} = {{
    isNormalUser = true;
    group = "{user}";
    extraGroups = [ "wheel" "networkmanager" ];
  }};
  users.groups.{user} = {{ }};

  # ── System packages (managed by i-nix) ──
  # Use: i-nix install <package>
  environment.systemPackages = with pkgs; [
  ];

  # ── Services ──
  # Use: i-nix enable ssh

  # ── Programs ──
  # Use: i-nix enable firefox

  # ── Filesystems ──
  # Configure after disk partitioning:
  # fileSystems."/" = {{ device = "/dev/disk/by-label/nixos"; fsType = "ext4"; }};

  # ── Profiles ──
  # Import feature bundles:
  # imports = [ ../profiles/desktop.nix ];

  # ── Modules ──
  # Import reusable modules:
  # imports = [ ../modules/system/default.nix ];
}}
"#,
            host = self.hostname,
            user = self.username
        );
        std::fs::write(
            flake_dir.join(format!("systems/{}/default.nix", self.hostname)),
            system_nix,
        )?;

        // ── systems/<hostname>/hardware.nix (placeholder) ──
        let hardware_nix = format!(
            r#"# Hardware configuration for: {host}
# Generate with: nixos-generate-config --show-hardware-config > hardware.nix
# Or after install: cp /etc/nixos/hardware-configuration.nix ./hardware.nix

{{ config, pkgs, lib, ... }}: {{ }}
"#,
            host = self.hostname
        );
        std::fs::write(
            flake_dir.join(format!("systems/{}/hardware.nix", self.hostname)),
            hardware_nix,
        )?;

        // ── users/<username>/default.nix (entrypoint) ──
        let user_default = format!(
            r#"# i-nix home configuration for: {user}
# Entrypoint — imports per-category modules.

{{ config, pkgs, lib, ... }}:

{{
  home.username = "{user}";
  # homeDirectory is managed by NixOS when using home-manager.nixosModules
  home.stateVersion = "24.11";

  imports = [
    ./packages
    ./programs
    ./services
    ./desktop
    ./shells
    ./secrets
  ];
}}
"#,
            user = self.username
        );
        std::fs::write(
            flake_dir.join(format!("users/{}/default.nix", self.username)),
            user_default,
        )?;

        // ── users/<username>/packages/ ──
        let packages_dir = flake_dir.join(format!("users/{}/packages", self.username));
        std::fs::create_dir_all(&packages_dir)?;
        let packages_nix = format!(
            r#"# User packages for: {user}
# Managed by: i-nix install --user <package>

{{ config, pkgs, lib, ... }}:

{{
  home.packages = with pkgs; [
    # User packages go here
  ];
}}
"#,
            user = self.username
        );
        std::fs::write(packages_dir.join("default.nix"), packages_nix)?;

        // ── users/<username>/programs/ ──
        let programs_dir = flake_dir.join(format!("users/{}/programs", self.username));
        std::fs::create_dir_all(&programs_dir)?;
        let programs_nix = r#"# User programs configuration
# Enable programs here: i-nix enable --user <program>

{ config, pkgs, lib, ... }:

{
  # Example:
  # programs.firefox.enable = true;
  # programs.git = {
  #   enable = true;
  #   userName = "Your Name";
  #   userEmail = "you@example.com";
  # };
}
"#;
        std::fs::write(programs_dir.join("default.nix"), programs_nix)?;

        // ── users/<username>/services/ ──
        let services_dir = flake_dir.join(format!("users/{}/services", self.username));
        std::fs::create_dir_all(&services_dir)?;
        let services_nix = r#"# User services configuration
# User-level systemd services and daemons

{ config, pkgs, lib, ... }:

{
  # Example:
  # services.syncthing.enable = true;
}
"#;
        std::fs::write(services_dir.join("default.nix"), services_nix)?;

        // ── users/<username>/desktop/default.nix ──
        let desktop_default = format!(
            r#"# Desktop environment configuration for: {user}
# Import the DE you're using. Run `i-nix desktop detect` to auto-detect.

{{ config, pkgs, lib, ... }}:

{{
  # Uncomment the desktop you use:
  # imports = [ ./gnome.nix ];
  # imports = [ ./kde.nix ];
  # imports = [ ./hyprland.nix ];
  # imports = [ ./sway.nix ];
}}
"#,
            user = self.username
        );
        std::fs::write(
            flake_dir.join(format!("users/{}/desktop/default.nix", self.username)),
            desktop_default,
        )?;

        // ── desktop environment stubs ──
        let gnome_stub = r#"# GNOME desktop configuration
# Generated with: nix-my-gnome (dconf dump → Nix)
# Run: dconf dump / | nix run github:stefan-hacks/nix-my-gnome -- -o ./gnome.nix

{ config, pkgs, lib, ... }:

{
  # Import GNOME settings generated by nix-my-gnome:
  # imports = [ ./gnome-settings/default.nix ];

  # Or set dconf manually:
  # dconf.settings = {
  #   "org/gnome/desktop/interface" = {
  #     clock-format = "24h";
  #   };
  # };
}
"#;
        let kde_stub = r#"# KDE Plasma desktop configuration
# Generated with: plasma-manager
# See: https://github.com/pjones/plasma-manager

{ config, pkgs, lib, ... }:

{
}
"#;
        let hyprland_stub = r#"# Hyprland desktop configuration
{ config, pkgs, lib, ... }:

{
  # wayland.windowManager.hyprland.enable = true;
  # wayland.windowManager.hyprland.settings = {
  #   general = {
  #     gaps_in = 5;
  #     gaps_out = 10;
  #   };
  # };
}
"#;
        let sway_stub = r#"# Sway desktop configuration
{ config, pkgs, lib, ... }:

{
  # wayland.windowManager.sway.enable = true;
}
"#;
        std::fs::write(
            flake_dir.join(format!("users/{}/desktop/gnome.nix", self.username)),
            gnome_stub,
        )?;
        std::fs::write(
            flake_dir.join(format!("users/{}/desktop/kde.nix", self.username)),
            kde_stub,
        )?;
        std::fs::write(
            flake_dir.join(format!("users/{}/desktop/hyprland.nix", self.username)),
            hyprland_stub,
        )?;
        std::fs::write(
            flake_dir.join(format!("users/{}/desktop/sway.nix", self.username)),
            sway_stub,
        )?;

        // ── users/<username>/shells/default.nix ──
        let shells_default = r#"# Shell configuration
# Enable your preferred shell here

{ config, pkgs, lib, ... }:

{
  # programs.bash.enable = true;
  # programs.zsh.enable = true;
  # programs.fish.enable = true;
  # programs.starship.enable = true;
}
"#;
        std::fs::write(
            flake_dir.join(format!("users/{}/shells/default.nix", self.username)),
            shells_default,
        )?;

        // ── users/<username>/secrets/default.nix ──
        let secrets_default = r#"# Secrets configuration
# Use sops-nix or agenix for secret management

{ config, pkgs, lib, ... }:

{
  # Example with sops-nix:
  # sops.defaultSopsFile = ./secrets.yaml;
  # sops.secrets."api-key" = { };
}
"#;
        std::fs::write(
            flake_dir.join(format!("users/{}/secrets/default.nix", self.username)),
            secrets_default,
        )?;

        // ── profiles/ ──
        let core_profile = r#"# Core profile — minimal headless system
# Suitable for servers, VMs, containers

{ config, pkgs, lib, ... }:

{
  # SSH access
  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "prohibit-password";

  # Basic firewall
  networking.firewall.enable = true;
}
"#;
        let desktop_profile = r#"# Desktop profile — graphical system
# Suitable for laptops and workstations

{ config, pkgs, lib, ... }:

{
  # Enable a display manager and desktop environment
  # services.xserver.enable = true;
  # services.xserver.displayManager.gdm.enable = true;
  # services.xserver.desktopManager.gnome.enable = true;

  # Sound
  # services.pipewire.enable = true;
  # services.pipewire.alsa.enable = true;
  # services.pipewire.pulse.enable = true;

  # Bluetooth
  # hardware.bluetooth.enable = true;
}
"#;
        let dev_profile = r#"# Development profile — dev tools
# Suitable for developer workstations

{ config, pkgs, lib, ... }:

{
  # Development tools available system-wide
  # programs.git.enable = true;
  # programs.vim.defaultEditor = true;

  # Docker
  # virtualisation.docker.enable = true;
}
"#;
        let gaming_profile = r#"# Gaming profile — gaming stack
{ config, pkgs, lib, ... }:

{
  # programs.steam.enable = true;
  # hardware.graphics.enable = true;
}
"#;
        let server_profile = r#"# Server profile — services and daemons
{ config, pkgs, lib, ... }:

{
  # services.nginx.enable = true;
  # services.postgresql.enable = true;
}
"#;
        std::fs::write(flake_dir.join("profiles/core.nix"), core_profile)?;
        std::fs::write(flake_dir.join("profiles/desktop.nix"), desktop_profile)?;
        std::fs::write(flake_dir.join("profiles/development.nix"), dev_profile)?;
        std::fs::write(flake_dir.join("profiles/gaming.nix"), gaming_profile)?;
        std::fs::write(flake_dir.join("profiles/server.nix"), server_profile)?;

        // ── modules/system/ ──
        let system_modules = r#"# Reusable NixOS system modules
# Place modules here that configure system-level concerns.
# Each module should be self-contained and reusable across hosts.

{ config, pkgs, lib, ... }:

{
  # Example: network module
  # networking.networkmanager.enable = true;
}
"#;
        let home_modules = r#"# Reusable Home Manager modules
# Place modules here that configure user-level concerns.
# Each module should be self-contained and reusable across users.

{ config, pkgs, lib, ... }:

{
  # Example: kitty module
  # programs.kitty.enable = true;
  # programs.kitty.settings.font_size = 12;
}
"#;
        std::fs::write(flake_dir.join("modules/system/default.nix"), system_modules)?;
        std::fs::write(flake_dir.join("modules/home/default.nix"), home_modules)?;

        // ── overlays, pkgs, lib ──
        std::fs::write(flake_dir.join("overlays/default.nix"), "final: prev: { }\n")?;
        std::fs::write(flake_dir.join("pkgs/default.nix"), "{ pkgs }: { }\n")?;
        std::fs::write(flake_dir.join("lib/helpers.nix"), "{ lib, ... }: { }\n")?;

        // .gitignore
        std::fs::write(flake_dir.join(".gitignore"), "result\nresult-*\n")?;

        Ok(())
    }

    // ── Path helpers (production-grade structure) ──

    fn systems_nix(&self) -> std::path::PathBuf {
        self.config_dir
            .join(format!("flake/systems/{}/default.nix", self.hostname))
    }

    fn packages_nix(&self) -> std::path::PathBuf {
        self.config_dir
            .join(format!("flake/users/{}/packages/default.nix", self.username))
    }

    /// Add a package to the declarative configuration.
    pub fn add_package(&self, name: &str, _attr: &str, target: InstallTarget) -> Result<()> {
        match target {
            InstallTarget::System => {
                let path = self.systems_nix();
                let mut packages = read_system_packages(&path)?;
                if !packages.contains(&name.to_string()) {
                    packages.push(name.to_string());
                }
                let entries: Vec<PackageEntry> = packages
                    .into_iter()
                    .map(|n| PackageEntry {
                        name: n,
                        comment: None,
                    })
                    .collect();
                write_system_packages(&path, &entries)?;
            }
            InstallTarget::User => {
                let path = self.packages_nix();
                let mut packages = read_home_packages(&path)?;
                if !packages.contains(&name.to_string()) {
                    packages.push(name.to_string());
                }
                let entries: Vec<PackageEntry> = packages
                    .into_iter()
                    .map(|n| PackageEntry {
                        name: n,
                        comment: None,
                    })
                    .collect();
                write_home_packages(&path, &entries)?;
            }
        }
        Ok(())
    }

    /// Remove a package from the declarative configuration.
    pub fn remove_package(&self, name: &str, target: InstallTarget) -> Result<bool> {
        let removed = match target {
            InstallTarget::System => {
                let path = self.systems_nix();
                let mut packages = read_system_packages(&path)?;
                let before = packages.len();
                packages.retain(|p| p != name);
                let after = packages.len();
                if after < before {
                    let entries: Vec<PackageEntry> = packages
                        .into_iter()
                        .map(|n| PackageEntry {
                            name: n,
                            comment: None,
                        })
                        .collect();
                    write_system_packages(&path, &entries)?;
                    true
                } else {
                    false
                }
            }
            InstallTarget::User => {
                let path = self.packages_nix();
                let mut packages = read_home_packages(&path)?;
                let before = packages.len();
                packages.retain(|p| p != name);
                let after = packages.len();
                if after < before {
                    let entries: Vec<PackageEntry> = packages
                        .into_iter()
                        .map(|n| PackageEntry {
                            name: n,
                            comment: None,
                        })
                        .collect();
                    write_home_packages(&path, &entries)?;
                    true
                } else {
                    false
                }
            }
        };
        Ok(removed)
    }

    fn programs_nix(&self) -> std::path::PathBuf {
        self.config_dir
            .join(format!("flake/users/{}/programs/default.nix", self.username))
    }

    // ── Enable / Disable ──

    /// Enable a service or program in the configuration.
    pub fn enable(&self, module_path: &str, user: bool) -> Result<()> {
        let path = if user {
            self.programs_nix()
        } else {
            self.systems_nix()
        };
        let source = std::fs::read_to_string(&path)?;
        let new_source = crate::nixast::add_enable_line(&source, module_path)?;
        if new_source != source {
            std::fs::write(path, new_source)?;
        }
        Ok(())
    }

    /// Disable (remove) a service or program enable line.
    pub fn disable(&self, module_path: &str, user: bool) -> Result<bool> {
        let path = if user {
            self.programs_nix()
        } else {
            self.systems_nix()
        };
        let source = std::fs::read_to_string(&path)?;
        let new_source = crate::nixast::remove_enable_line(&source, module_path)?;
        let changed = new_source != source;
        if changed {
            std::fs::write(path, new_source)?;
        }
        Ok(changed)
    }
}
